version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      network:
        ipv4_address: 10.5.0.6

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      network:
        ipv4_address: 10.5.0.5

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes:
  postgres_data: